List<Map<String, String>> countryList = [
  {"name": "Afghanistan", "code": "+93", "icon": "🇦🇫"},
  {"name": "Albania", "code": "+355", "icon": "🇦🇱"},
  {"name": "Algeria", "code": "+213", "icon": "🇩🇿"},
  {"name": "Andorra", "code": "+376", "icon": "🇦🇩"},
  {"name": "Angola", "code": "+244", "icon": "🇦🇴"},
  {"name": "Antigua and Barbuda", "code": "+1-268", "icon": "🇦🇬"},
  {"name": "Argentina", "code": "+54", "icon": "🇦🇷"},
  {"name": "Armenia", "code": "+374", "icon": "🇦🇲"},
  {"name": "Australia", "code": "+61", "icon": "🇦🇺"},
  {"name": "Austria", "code": "+43", "icon": "🇦🇹"},
  {"name": "Azerbaijan", "code": "+994", "icon": "🇦🇿"},
  {"name": "Bahamas", "code": "+1-242", "icon": "🇧🇸"},
  {"name": "Bahrain", "code": "+973", "icon": "🇧🇭"},
  {"name": "Bangladesh", "code": "+880", "icon": "🇧🇩"},
  {"name": "Barbados", "code": "+1-246", "icon": "🇧🇧"},
  {"name": "Belarus", "code": "+375", "icon": "🇧🇾"},
  {"name": "Belgium", "code": "+32", "icon": "🇧🇪"},
  {"name": "Belize", "code": "+501", "icon": "🇧🇿"},
  {"name": "Benin", "code": "+229", "icon": "🇧🇯"},
  {"name": "Bhutan", "code": "+975", "icon": "🇧🇹"},
  {"name": "Bolivia", "code": "+591", "icon": "🇧🇴"},
  {"name": "Bosnia and Herzegovina", "code": "+387", "icon": "🇧🇦"},
  {"name": "Botswana", "code": "+267", "icon": "🇧🇼"},
  {"name": "Brazil", "code": "+55", "icon": "🇧🇷"},
  {"name": "Brunei", "code": "+673", "icon": "🇧🇳"},
  {"name": "Bulgaria", "code": "+359", "icon": "🇧🇬"},
  {"name": "Burkina Faso", "code": "+226", "icon": "🇧🇫"},
  {"name": "Burundi", "code": "+257", "icon": "🇧🇮"},
  {"name": "Cambodia", "code": "+855", "icon": "🇰🇭"},
  {"name": "Cameroon", "code": "+237", "icon": "🇨🇲"},
  // {"name": "Canada", "code": "+1", "icon": "🇨🇦"},
  {"name": "Cape Verde", "code": "+238", "icon": "🇨🇻"},
  {"name": "Central African Republic", "code": "+236", "icon": "🇨🇫"},
  {"name": "Chad", "code": "+235", "icon": "🇹🇩"},
  {"name": "Chile", "code": "+56", "icon": "🇨🇱"},
  {"name": "China", "code": "+86", "icon": "🇨🇳"},
  {"name": "Colombia", "code": "+57", "icon": "🇨🇴"},
  {"name": "Comoros", "code": "+269", "icon": "🇰🇲"},
  {"name": "Congo", "code": "+242", "icon": "🇨🇬"},
  {"name": "Costa Rica", "code": "+506", "icon": "🇨🇷"},
  {"name": "Croatia", "code": "+385", "icon": "🇭🇷"},
  {"name": "Cuba", "code": "+53", "icon": "🇨🇺"},
  {"name": "Cyprus", "code": "+357", "icon": "🇨🇾"},
  {"name": "Czech Republic", "code": "+420", "icon": "🇨🇿"},
  {"name": "Denmark", "code": "+45", "icon": "🇩🇰"},
  {"name": "Djibouti", "code": "+253", "icon": "🇩🇯"},
  {"name": "Dominica", "code": "+1-767", "icon": "🇩🇲"},
  {"name": "Dominican Republic", "code": "+1-809", "icon": "🇩🇴"},
  {"name": "East Timor", "code": "+670", "icon": "🇹🇱"},
  {"name": "Ecuador", "code": "+593", "icon": "🇪🇨"},
  {"name": "Egypt", "code": "+20", "icon": "🇪🇬"},
  {"name": "El Salvador", "code": "+503", "icon": "🇸🇻"},
  {"name": "Equatorial Guinea", "code": "+240", "icon": "🇬🇶"},
  {"name": "Eritrea", "code": "+291", "icon": "🇪🇷"},
  {"name": "Estonia", "code": "+372", "icon": "🇪🇪"},
  {"name": "Ethiopia", "code": "+251", "icon": "🇪🇹"},
  {"name": "Fiji", "code": "+679", "icon": "🇫🇯"},
  {"name": "Finland", "code": "+358", "icon": "🇫🇮"},
  {"name": "France", "code": "+33", "icon": "🇫🇷"},
  {"name": "Gabon", "code": "+241", "icon": "🇬🇦"},
  {"name": "Gambia", "code": "+220", "icon": "🇬🇲"},
  {"name": "Georgia", "code": "+995", "icon": "🇬🇪"},
  {"name": "Germany", "code": "+49", "icon": "🇩🇪"},
  {"name": "Ghana", "code": "+233", "icon": "🇬🇭"},
  {"name": "Greece", "code": "+30", "icon": "🇬🇷"},
  {"name": "Grenada", "code": "+1-473", "icon": "🇬🇩"},
  {"name": "Guatemala", "code": "+502", "icon": "🇬🇹"},
  {"name": "Guinea", "code": "+224", "icon": "🇬🇳"},
  {"name": "Guinea-Bissau", "code": "+245", "icon": "🇬🇼"},
  {"name": "Guyana", "code": "+592", "icon": "🇬🇾"},
  {"name": "Haiti", "code": "+509", "icon": "🇭🇹"},
  {"name": "Honduras", "code": "+504", "icon": "🇭🇳"},
  {"name": "Hungary", "code": "+36", "icon": "🇭🇺"},
  {"name": "Iceland", "code": "+354", "icon": "🇮🇸"},
  {"name": "India", "code": "+91", "icon": "🇮🇳"},
  {"name": "Indonesia", "code": "+62", "icon": "🇮🇩"},
  {"name": "Iran", "code": "+98", "icon": "🇮🇷"},
  {"name": "Iraq", "code": "+964", "icon": "🇮🇶"},
  {"name": "Ireland", "code": "+353", "icon": "🇮🇪"},
  {"name": "Israel", "code": "+972", "icon": "🇮🇱"},
  {"name": "Italy", "code": "+39", "icon": "🇮🇹"},
  {"name": "Jamaica", "code": "+1-876", "icon": "🇯🇲"},
  {"name": "Japan", "code": "+81", "icon": "🇯🇵"},
  {"name": "Jordan", "code": "+962", "icon": "🇯🇴"},
  {"name": "Kazakhstan", "code": "+7", "icon": "🇰🇿"},
  {"name": "Kenya", "code": "+254", "icon": "🇰🇪"},
  {"name": "Kiribati", "code": "+686", "icon": "🇰🇮"},
  {"name": "North Korea", "code": "+850", "icon": "🇰🇵"},
  {"name": "South Korea", "code": "+82", "icon": "🇰🇷"},
  {"name": "Kuwait", "code": "+965", "icon": "🇰🇼"},
  {"name": "Kyrgyzstan", "code": "+996", "icon": "🇰🇬"},
  {"name": "Laos", "code": "+856", "icon": "🇱🇦"},
  {"name": "Latvia", "code": "+371", "icon": "🇱🇻"},
  {"name": "Lebanon", "code": "+961", "icon": "🇱🇧"},
  {"name": "Lesotho", "code": "+266", "icon": "🇱🇸"},
  {"name": "Liberia", "code": "+231", "icon": "🇱🇷"},
  {"name": "Libya", "code": "+218", "icon": "🇱🇾"},
  {"name": "Liechtenstein", "code": "+423", "icon": "🇱🇮"},
  {"name": "Lithuania", "code": "+370", "icon": "🇱🇹"},
  {"name": "Luxembourg", "code": "+352", "icon": "🇱🇺"},
  {"name": "North Macedonia", "code": "+389", "icon": "🇲🇰"},
  {"name": "Madagascar", "code": "+261", "icon": "🇲🇬"},
  {"name": "Malawi", "code": "+265", "icon": "🇲🇼"},
  {"name": "Malaysia", "code": "+60", "icon": "🇲🇾"},
  {"name": "Maldives", "code": "+960", "icon": "🇲🇻"},
  {"name": "Mali", "code": "+223", "icon": "🇲🇱"},
  {"name": "Malta", "code": "+356", "icon": "🇲🇹"},
  {"name": "Marshall Islands", "code": "+692", "icon": "🇲🇭"},
  {"name": "Mauritania", "code": "+222", "icon": "🇲🇷"},
  {"name": "Mauritius", "code": "+230", "icon": "🇲🇺"},
  {"name": "Mexico", "code": "+52", "icon": "🇲🇽"},
  {"name": "Micronesia", "code": "+691", "icon": "🇫🇲"},
  {"name": "Moldova", "code": "+373", "icon": "🇲🇩"},
  {"name": "Monaco", "code": "+377", "icon": "🇲🇨"},
  {"name": "Mongolia", "code": "+976", "icon": "🇲🇳"},
  {"name": "Montenegro", "code": "+382", "icon": "🇲🇪"},
  {"name": "Morocco", "code": "+212", "icon": "🇲🇦"},
  {"name": "Mozambique", "code": "+258", "icon": "🇲🇿"},
  {"name": "Myanmar", "code": "+95", "icon": "🇲🇲"},
  {"name": "Namibia", "code": "+264", "icon": "🇳🇦"},
  {"name": "Nauru", "code": "+674", "icon": "🇳🇷"},
  {"name": "Nepal", "code": "+977", "icon": "🇳🇵"},
  {"name": "Netherlands", "code": "+31", "icon": "🇳🇱"},
  {"name": "New Zealand", "code": "+64", "icon": "🇳🇿"},
  {"name": "Nicaragua", "code": "+505", "icon": "🇳🇮"},
  {"name": "Niger", "code": "+227", "icon": "🇳🇪"},
  {"name": "Nigeria", "code": "+234", "icon": "🇳🇬"},
  {"name": "Norway", "code": "+47", "icon": "🇳🇴"},
  {"name": "Oman", "code": "+968", "icon": "🇴🇲"},
  {"name": "Pakistan", "code": "+92", "icon": "🇵🇰"},
  {"name": "Palau", "code": "+680", "icon": "🇵🇼"},
  {"name": "Palestine", "code": "+970", "icon": "🇵🇸"},
  {"name": "Panama", "code": "+507", "icon": "🇵🇦"},
  {"name": "Papua New Guinea", "code": "+675", "icon": "🇵🇬"},
  {"name": "Paraguay", "code": "+595", "icon": "🇵🇾"},
  {"name": "Peru", "code": "+51", "icon": "🇵🇪"},
  {"name": "Philippines", "code": "+63", "icon": "🇵🇭"},
  {"name": "Poland", "code": "+48", "icon": "🇵🇱"},
  {"name": "Portugal", "code": "+351", "icon": "🇵🇹"},
  {"name": "Qatar", "code": "+974", "icon": "🇶🇦"},
  {"name": "Romania", "code": "+40", "icon": "🇷🇴"},
  {"name": "Russia", "code": "+7", "icon": "🇷🇺"},
  {"name": "Rwanda", "code": "+250", "icon": "🇷🇼"},
  {"name": "Saint Kitts and Nevis", "code": "+1-869", "icon": "🇰🇳"},
  {"name": "Saint Lucia", "code": "+1-758", "icon": "🇱🇨"},
  {
    "name": "Saint Vincent and the Grenadines",
    "code": "+1-784",
    "icon": "🇻🇨",
  },
  {"name": "Samoa", "code": "+685", "icon": "🇼🇸"},
  {"name": "San Marino", "code": "+378", "icon": "🇸🇲"},
  {"name": "Sao Tome and Principe", "code": "+239", "icon": "🇸🇹"},
  {"name": "Saudi Arabia", "code": "+966", "icon": "🇸🇦"},
  {"name": "Senegal", "code": "+221", "icon": "🇸🇳"},
  {"name": "Serbia", "code": "+381", "icon": "🇷🇸"},
  {"name": "Seychelles", "code": "+248", "icon": "🇸🇨"},
  {"name": "Sierra Leone", "code": "+232", "icon": "🇸🇱"},
  {"name": "Singapore", "code": "+65", "icon": "🇸🇬"},
  {"name": "Slovakia", "code": "+421", "icon": "🇸🇰"},
  {"name": "Slovenia", "code": "+386", "icon": "🇸🇮"},
  {"name": "Solomon Islands", "code": "+677", "icon": "🇸🇧"},
  {"name": "Somalia", "code": "+252", "icon": "🇸🇴"},
  {"name": "South Africa", "code": "+27", "icon": "🇿🇦"},
  {"name": "South Sudan", "code": "+211", "icon": "🇸🇸"},
  {"name": "Spain", "code": "+34", "icon": "🇪🇸"},
  {"name": "Sri Lanka", "code": "+94", "icon": "🇱🇰"},
  {"name": "Sudan", "code": "+249", "icon": "🇸🇩"},
  {"name": "Suriname", "code": "+597", "icon": "🇸🇷"},
  {"name": "Sweden", "code": "+46", "icon": "🇸🇪"},
  {"name": "Switzerland", "code": "+41", "icon": "🇨🇭"},
  {"name": "Syria", "code": "+963", "icon": "🇸🇾"},
  {"name": "Taiwan", "code": "+886", "icon": "🇹🇼"},
  {"name": "Tajikistan", "code": "+992", "icon": "🇹🇯"},
  {"name": "Tanzania", "code": "+255", "icon": "🇹🇿"},
  {"name": "Thailand", "code": "+66", "icon": "🇹🇭"},
  {"name": "Togo", "code": "+228", "icon": "🇹🇬"},
  {"name": "Tonga", "code": "+676", "icon": "🇹🇴"},
  {"name": "Trinidad and Tobago", "code": "+1-868", "icon": "🇹🇹"},
  {"name": "Tunisia", "code": "+216", "icon": "🇹🇳"},
  {"name": "Turkey", "code": "+90", "icon": "🇹🇷"},
  {"name": "Turkmenistan", "code": "+993", "icon": "🇹🇲"},
  {"name": "Tuvalu", "code": "+688", "icon": "🇹🇻"},
  {"name": "Uganda", "code": "+256", "icon": "🇺🇬"},
  {"name": "Ukraine", "code": "+380", "icon": "🇺🇦"},
  {"name": "United Arab Emirates", "code": "+971", "icon": "🇦🇪"},
  {"name": "United Kingdom", "code": "+44", "icon": "🇬🇧"},
  {"name": "US/Canada", "code": "+1", "icon": "🇺🇸"},
  {"name": "Uruguay", "code": "+598", "icon": "🇺🇾"},
  {"name": "Uzbekistan", "code": "+998", "icon": "🇺🇿"},
  {"name": "Vanuatu", "code": "+678", "icon": "🇻🇺"},
  {"name": "Vatican City", "code": "+379", "icon": "🇻🇦"},
  {"name": "Venezuela", "code": "+58", "icon": "🇻🇪"},
  {"name": "Vietnam", "code": "+84", "icon": "🇻🇳"},
  {"name": "Yemen", "code": "+967", "icon": "🇾🇪"},
  {"name": "Zambia", "code": "+260", "icon": "🇿🇲"},
  {"name": "Zimbabwe", "code": "+263", "icon": "🇿🇼"},
];
